# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CSV_ReadWriteDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  #pod 'CSVParser', :path => '/Users/pawankumar/Desktop/CSVPod/CSVParser/CSVParser.podspec'
  pod 'CSVParser'

  # Pods for CSV_ReadWriteDemo

  target 'CSV_ReadWriteDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSV_ReadWriteDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
